### ISSUE TITLE
Suddently KeeAgent is not loading anymore

### ISSUE THREAD

**Issue by guptamp** [dlech/KeeAgent#111]
I have no clue what happened, everything was working fine and this morning it got this.
I don´t think i changed anything but i noticed i had a sync issue with my keepass.config.xml.
Not sure if that could be related....

below the output from: keepass --debug --saveplgxcr
1. Error message box:
```[Window Title]
KeePass

[Content]
The following plugin is incompatible with the current KeePass version:
D:\CloudStation\keepass\KeePass\plugins\KeeAgent.plgx

Have a look at the plugin's website for an appropriate version.

[Expanded Information]
ResX file Type System.Drawing.Bitmap, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a cannot be located. Line 123, position 5. cannot be parsed.
System.Windows.Forms
   at System.Resources.ResXResourceReader.ParseXml(XmlTextReader reader)
   at System.Resources.ResXResourceReader.EnsureResData()
   at System.Resources.ResXResourceReader.GetEnumerator()
   at KeePass.Plugins.PlgxPlugin.CompileEmbeddedRes(PlgxPluginInfo plgx)
   at KeePass.Plugins.PlgxPlugin.Compile(String strTmpRoot, PlgxPluginInfo plgx, String strBuildPre, String strBuildPost)
   at KeePass.Plugins.PlgxPlugin.ReadFile(BinaryReader br, PlgxPluginInfo plgx, IStatusLogger slStatus)
   at KeePass.Plugins.PlgxPlugin.LoadPriv(String strFilePath, IStatusLogger slStatus, Boolean bAllowCached, Boolean bAllowCompile, Boolean bAllowLoad, TextWriter twLog)
   at KeePass.Plugins.PlgxPlugin.Load(String strFilePath, IStatusLogger slStatus)
Void ParseXml(System.Xml.XmlTextReader)


Inner:
Type System.Drawing.Bitmap, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a cannot be located. Line 123, position 5.

[^] Details  [OK]```

2. Error Message box
[Window Title]
KeePass

[Content]
The following plugin is incompatible with the current KeePass version:
D:\CloudStation\keepass\KeePass\plugins\KeeOtp.plgx

Have a look at the plugin's website for an appropriate version.

[Expanded Information]
Operation is not valid due to the current state of the object.
KeePass
   at KeePass.Plugins.PlgxPlugin.Compile(String strTmpRoot, PlgxPluginInfo plgx, String strBuildPre, String strBuildPost)
   at KeePass.Plugins.PlgxPlugin.ReadFile(BinaryReader br, PlgxPluginInfo plgx, IStatusLogger slStatus)
   at KeePass.Plugins.PlgxPlugin.LoadPriv(String strFilePath, IStatusLogger slStatus, Boolean bAllowCached, Boolean bAllowCompile, Boolean bAllowLoad, TextWriter twLog)
   at KeePass.Plugins.PlgxPlugin.Load(String strFilePath, IStatusLogger slStatus)
System.String Compile(System.String, KeePass.Plugins.PlgxPluginInfo, System.String, System.String)

[^] Details  [OK]

Log:
D:\CloudStation\keepass\KeePass> "C:\Windows\Microsoft.NET\Framework64\v3.5\csc.exe" /t:library /utf8output /R:"System.dll" /R:"System.Data.dll" /R:"System.Drawing.dll" /R:"System.Windows.Forms.dll" /R:"System.Xml.dll" /R:"D:\CloudStation\keepass\KeePass\KeePass.exe" /R:"C:\Users\michael\AppData\Local\KeePass\PluginCache\qtWS8SGW2K7hrxbLqJJc\OtpSharp.dll" /R:"System.Core.dll" /out:"C:\Users\michael\AppData\Local\Temp\C25DA3980A60B2449AB75656CEEDAEB8\KeeOtp.dll" /debug- /optimize+ /res:"C:\Users\michael\AppData\Local\Temp\C25DA3980A60B2449AB75656CEEDAEB8\KeeOtp\KeeOtp.OtpInformation.resources" /res:"C:\Users\michael\AppData\Local\Temp\C25DA3980A60B2449AB75656CEEDAEB8\KeeOtp\KeeOtp.Resources.resources" /res:"C:\Users\michael\AppData\Local\Temp\C25DA3980A60B2449AB75656CEEDAEB8\KeeOtp\KeeOtp.ShowOneTimePasswords.resources" /res:"C:\Users\michael\AppData\Local\Temp\C25DA3980A60B2449AB75656CEEDAEB8\KeeOtp\KeeOtp.Troubleshooting.resources"  "C:\Users\michael\AppData\Local\Temp\C25DA3980A60B2449AB75656CEEDAEB8\KeeOtp\AsyncOperation.cs" "C:\Users\michael\AppData\Local\Temp\C25DA3980A60B2449AB75656CEEDAEB8\KeeOtp\OtpInformation.cs" "C:\Users\michael\AppData\Local\Temp\C25DA3980A60B2449AB75656CEEDAEB8\KeeOtp\OtpInformation.Designer.cs" "C:\Users\michael\AppData\Local\Temp\C25DA3980A60B2449AB75656CEEDAEB8\KeeOtp\OtpType.cs" "C:\Users\michael\AppData\Local\Temp\C25DA3980A60B2449AB75656CEEDAEB8\KeeOtp\KeeOtpExt.cs" "C:\Users\michael\AppData\Local\Temp\C25DA3980A60B2449AB75656CEEDAEB8\KeeOtp\OtpAuthData.cs" "C:\Users\michael\AppData\Local\Temp\C25DA3980A60B2449AB75656CEEDAEB8\KeeOtp\Resources.Designer.cs" "C:\Users\michael\AppData\Local\Temp\C25DA3980A60B2449AB75656CEEDAEB8\KeeOtp\ShowOneTimePasswords.cs" "C:\Users\michael\AppData\Local\Temp\C25DA3980A60B2449AB75656CEEDAEB8\KeeOtp\ShowOneTimePasswords.Designer.cs" "C:\Users\michael\AppData\Local\Temp\C25DA3980A60B2449AB75656CEEDAEB8\KeeOtp\Properties\AssemblyInfo.cs" "C:\Users\michael\AppData\Local\Temp\C25DA3980A60B2449AB75656CEEDAEB8\KeeOtp\Troubleshooting.cs" "C:\Users\michael\AppData\Local\Temp\C25DA3980A60B2449AB75656CEEDAEB8\KeeOtp\Troubleshooting.Designer.cs"


Microsoft (R) Visual C# 2008 Compiler version 3.5.30729.6400
for Microsoft (R) .NET Framework version 3.5
Copyright (C) Microsoft Corporation. All rights reserved.

c:\Users\michael\AppData\Local\Temp\C25DA3980A60B2449AB75656CEEDAEB8\KeeOtp\KeeOtpExt.cs(62,59): error CS1026: ) expected
c:\Users\michael\AppData\Local\Temp\C25DA3980A60B2449AB75656CEEDAEB8\KeeOtp\KeeOtpExt.cs(62,59): error CS1525: Invalid expression term ':'
c:\Users\michael\AppData\Local\Temp\C25DA3980A60B2449AB75656CEEDAEB8\KeeOtp\KeeOtpExt.cs(62,61): error CS1002: ; expected
c:\Users\michael\AppData\Local\Temp\C25DA3980A60B2449AB75656CEEDAEB8\KeeOtp\KeeOtpExt.cs(62,70): error CS1002: ; expected
c:\Users\michael\AppData\Local\Temp\C25DA3980A60B2449AB75656CEEDAEB8\KeeOtp\KeeOtpExt.cs(62,70): error CS1525: Invalid expression term ','
c:\Users\michael\AppData\Local\Temp\C25DA3980A60B2449AB75656CEEDAEB8\KeeOtp\KeeOtpExt.cs(62,72): error CS1002: ; expected
c:\Users\michael\AppData\Local\Temp\C25DA3980A60B2449AB75656CEEDAEB8\KeeOtp\KeeOtpExt.cs(62,91): error CS1002: ; expected
c:\Users\michael\AppData\Local\Temp\C25DA3980A60B2449AB75656CEEDAEB8\KeeOtp\KeeOtpExt.cs(62,91): error CS1525: Invalid expression term ')'
c:\Users\michael\AppData\Local\Temp\C25DA3980A60B2449AB75656CEEDAEB8\KeeOtp\KeeOtpExt.cs(112,55): error CS1026: ) expected
c:\Users\michael\AppData\Local\Temp\C25DA3980A60B2449AB75656CEEDAEB8\KeeOtp\KeeOtpExt.cs(112,55): error CS1525: Invalid expression term ':'
c:\Users\michael\AppData\Local\Temp\C25DA3980A60B2449AB75656CEEDAEB8\KeeOtp\KeeOtpExt.cs(112,57): error CS1002: ; expected
c:\Users\michael\AppData\Local\Temp\C25DA3980A60B2449AB75656CEEDAEB8\KeeOtp\KeeOtpExt.cs(112,66): error CS1002: ; expected
c:\Users\michael\AppData\Local\Temp\C25DA3980A60B2449AB75656CEEDAEB8\KeeOtp\KeeOtpExt.cs(112,66): error CS1525: Invalid expression term ','
c:\Users\michael\AppData\Local\Temp\C25DA3980A60B2449AB75656CEEDAEB8\KeeOtp\KeeOtpExt.cs(112,68): error CS1002: ; expected
c:\Users\michael\AppData\Local\Temp\C25DA3980A60B2449AB75656CEEDAEB8\KeeOtp\KeeOtpExt.cs(112,87): error CS1002: ; expected
c:\Users\michael\AppData\Local\Temp\C25DA3980A60B2449AB75656CEEDAEB8\KeeOtp\KeeOtpExt.cs(112,87): error CS1525: Invalid expression term ')'
c:\Users\michael\AppData\Local\Temp\C25DA3980A60B2449AB75656CEEDAEB8\KeeOtp\ShowOneTimePasswords.cs(94,53): error CS1026: ) expected
c:\Users\michael\AppData\Local\Temp\C25DA3980A60B2449AB75656CEEDAEB8\KeeOtp\ShowOneTimePasswords.cs(94,53): error CS1525: Invalid expression term ':'
c:\Users\michael\AppData\Local\Temp\C25DA3980A60B2449AB75656CEEDAEB8\KeeOtp\ShowOneTimePasswords.cs(94,55): error CS1002: ; expected
c:\Users\michael\AppData\Local\Temp\C25DA3980A60B2449AB75656CEEDAEB8\KeeOtp\ShowOneTimePasswords.cs(94,69): error CS1002: ; expected
c:\Users\michael\AppData\Local\Temp\C25DA3980A60B2449AB75656CEEDAEB8\KeeOtp\ShowOneTimePasswords.cs(94,69): error CS1525: Invalid expression term ','
c:\Users\michael\AppData\Local\Temp\C25DA3980A60B2449AB75656CEEDAEB8\KeeOtp\ShowOneTimePasswords.cs(94,71): error CS1002: ; expected
c:\Users\michael\AppData\Local\Temp\C25DA3980A60B2449AB75656CEEDAEB8\KeeOtp\ShowOneTimePasswords.cs(94,95): error CS1002: ; expected
c:\Users\michael\AppData\Local\Temp\C25DA3980A60B2449AB75656CEEDAEB8\KeeOtp\ShowOneTimePasswords.cs(94,95): error CS1525: Invalid expression term ')'
c:\Users\michael\AppData\Local\KeePass\PluginCache\qtWS8SGW2K7hrxbLqJJc\OtpSharp.dll: warning CS1684: Reference to type '㸠~' claims it is defined in 'c:\Windows\Microsoft.NET\Framework64\v2.0.50727\mscorlib.dll', but it could not be found

**Comment by guptamp** [comment]
It was something weird in KeePass, i reinstalled it and now KeeAgent is working again...
