### ISSUE TITLE
KeeAgent in Agent mode fails Vagrant provisioning (ruby net-ssh error: could not get identity count)

### ISSUE THREAD

**Issue by taurus-forever** [dlech/KeeAgent#130]
Hi,

I have noticed an issue with KeeAgent in Agent mode on Linux Mint 17.2.
KeeAgent fails Vagrant provisioning which uses ruby net-ssh library.
Error is 'could not get identity count'.
I am not sure where to write bugreport, here or to net-ssh library, 
but while default agent works well, lets start here.

Steps to reproduce (fix HOST/USER/PASS):

```
23:23:05 ✔ me:/tmp$ sudo apt-get install ruby2.0 ruby-net-ssh
...
23:24:01 ✔ me:/tmp$ cat test.rb 
#!/usr/bin/env ruby
 require 'rubygems'
 require 'net/ssh'
 
 HOST = 'X.X.X.X'
 USER = 'root'
 PASS = 'bla-bla-bla'
 
 Net::SSH.start( HOST, USER, :password => PASS ) do|ssh|
 result = ssh.exec!('uname -a')
 puts result
 end
23:24:03 ✔ me:/tmp$ ruby2.0 test.rb 
Linux myserver  3.16-0.bpo.3-amd64 #1 SMP Debian 3.16.5-1~bpo70+1 (2014-11-02) x86_64 GNU/Linux
23:24:13 ✔ me:/tmp$ keepass2 & 
23:24:37 ✔ me:/tmp$ ruby2.0 test.rb 
/usr/lib/ruby/vendor_ruby/net/ssh/authentication/agent/socket.rb:90:in `identities': could not get identity count (Net::SSH::Authentication::AgentError)
	from /usr/lib/ruby/vendor_ruby/net/ssh/authentication/key_manager.rb:103:in `each_identity'
	from /usr/lib/ruby/vendor_ruby/net/ssh/authentication/methods/publickey.rb:19:in `authenticate'
	from /usr/lib/ruby/vendor_ruby/net/ssh/authentication/session.rb:78:in `block in authenticate'
	from /usr/lib/ruby/vendor_ruby/net/ssh/authentication/session.rb:65:in `each'
	from /usr/lib/ruby/vendor_ruby/net/ssh/authentication/session.rb:65:in `authenticate'
	from /usr/lib/ruby/vendor_ruby/net/ssh.rb:196:in `start'
	from test.rb:9:in `<main>'
23:24:39 ✘ me:/tmp$ 
```

Just in case:
```
23:28:30 ✘ me:/tmp$ echo $SSH_AUTH_SOCK
/run/user/1000/keeagent.socket
23:28:34 ✔ me:/tmp$ file /run/user/1000/keeagent.socket
/run/user/1000/keeagent.socket: socket 
23:28:38 ✔ me:/tmp$ 

23:30:02 ✔ me:/tmp$ unset SSH_AUTH_SOCK
23:30:13 ✔ me:/tmp$ ruby2.0 test.rb 
Linux myserver 3.16-0.bpo.3-amd64 #1 SMP Debian 3.16.5-1~bpo70+1 (2014-11-02) x86_64 GNU/Linux
23:30:15 ✔ me:/tmp$ 

```

Some deep debug from the library net-ssh:
```
D, [2015-11-08T23:31:32.090008 #27641] DEBUG -- net.ssh.authentication.agent[a1bc74]: connecting to ssh-agent
D, [2015-11-08T23:31:32.090130 #27641] DEBUG -- net.ssh.authentication.agent[a1bc74]: sending agent request 1 len 44
D, [2015-11-08T23:31:32.090619 #27641] DEBUG -- net.ssh.authentication.agent[a1bc74]: received agent packet 2 len 5
D, [2015-11-08T23:31:32.090688 #27641] DEBUG -- net.ssh.authentication.agent[a1bc74]: sending agent request 11 len 0
D, [2015-11-08T23:31:32.090758 #27641] DEBUG -- net.ssh.authentication.agent[a1bc74]: received agent packet 5 len 1

could not get identity count
```

Any ideas here? Tnx!

**Comment by taurus-forever** [comment]
Forget one more point, library sources (see function 'identities()'):
https://net-ssh.github.io/net-ssh/classes/Net/SSH/Authentication/Agent.html#method-i-connect-21

produces the error above in case:
```
# File lib/net/ssh/authentication/agent/socket.rb, line 90
def identities
  type, body = send_and_wait(SSH2_AGENT_REQUEST_IDENTITIES)
  raise AgentError, "could not get identity count" if agent_failed(type)
  ...
```

So, it looks like KeeAgent doesn't provide IDENTITIES... whatever it means.

**Comment by dlech** [comment]
It looks like the problem was in the [negotiate!](https://net-ssh.github.io/net-ssh/classes/Net/SSH/Authentication/Agent.html#method-i-negotiate-21) method. Apparently it is checking for an SSH agent that I am not familiar with that uses the same numeric identifier for a different message. I've added a workaround that checks for this and throws away the extra data.

Please upgrade to v0.7.11 and give it a try.

**Comment by taurus-forever** [comment]
Confirmed. The workaround hides an issue!
