### ISSUE TITLE
Exception when loading keys

### ISSUE THREAD

**Issue by montoner0** [dlech/KeeAgent#360]
After updating to 0.13.2 every attempt to load a key throws an exception:
```
KeeAgent: Error while loading key from entry '[entryname]'



Unexpected error



System.ArgumentException: settings has invalid private key location

Parameter name: settings

   at KeeAgent.ExtensionMethods.GetSshPrivateKey(EntrySettings settings, ProtectedBinaryDictionary binaries)

   at KeeAgent.ExtensionMethods.GetSshKey(PwEntry entry)

   at KeeAgent.KeeAgentExt.AddEntry(PwEntry entry, ICollection`1 constraints)

```

This is how the section in `KeyAgent.settings` looks:
```
  <PrivateKeyLocation>
    <SelectedType>attachment</SelectedType>
    <AttachmentName>[entry].ppk</AttachmentName>
    <SaveAttachmentToTempFile>false</SaveAttachmentToTempFile>
    <FileName />
  </PrivateKeyLocation>
```

**Comment by montoner0** [comment]
The same with 0.13.1. It seems I've used some unreleased version 0.13.0...

**Comment by dlech** [comment]
You can try replacing `PrivateKeyLocation` with `Location` or restore from backup.

**Comment by montoner0** [comment]
Thanks for the tip. It was enough to select the key again through the `Manage Key Files...` button.
