### ISSUE TITLE
Object rference not set to an instance of an object

### ISSUE THREAD

**Issue by gsommer** [dlech/KeeAgent#422]
Hi,

I installed the keeagent plugin on my Windows computer in a portable installation of Keepass Pro 2.56 (64 bit). When I try to configure it, I see a warning triangle next to Manage Keyfiles...

When I click anything I get "Object rference not set to an instance of an object".

Is there anything I can do about it? I tried to copy the dll to the plugin directory too, but maybe it needs to be installed somehow? I tis not mentioned in the documentation.

Kind Regards,
Gerhard

**Comment by mechgt** [comment]
Same, I'm getting this a lot on many different UI interactions with KeeAgent.  I've been using this plugin for years and this is new.  Below is the most recent crash.  I suspect that it has something to do with attachments not being named or parsed as expected, but that's a wild guess at this point.

```
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at KeeAgent.UI.EntryPanel.UpdateKeyInfo()
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
KeePass
    Assembly Version: 2.57.1.16889
    Win32 Version: 2.57.1.0
    CodeBase: file:///C:/Program%20Files/KeePass%20Password%20Safe%202/KeePass.exe
----------------------------------------
KeeAgent
    Assembly Version: 0.13.8.0
    Win32 Version: 0.13.8.0
    CodeBase: file:///C:/Program%20Files/KeePass%20Password%20Safe%202/Plugins/KeeAgent.dll

************** JIT Debugging **************

```
